[package]
name = "legura"
version = "0.0.1"
edition = "2021"
publish = false
default-run = "legura"

[workspace]

[dependencies]
axonyx-runtime = { version = "0.6.6", features = ["axum"] }
axonyx-ui = "0.0.85"
serde_json = "1"
anyhow = "1"
rusqlite = { version = "0.37", features = ["backup", "bundled"] }
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
